apiVersion: v1                  # 版本
kind: ReplicationController     # kind RC
metadata: 
  name: mysql                   # RC名称
spec:                           # spec相关属性
  replicas: 1                   # 期望副本数量
  selector: 
    app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec:
      containers: 
      - name: mysql
        image: mysql:5.7
        ports: 
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
